[2017-03-30 18:55:49,063] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-30 18:55:49,064] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-30 20:12:27,333] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-30 20:12:27,336] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-01 15:58:57,399] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-01 15:58:57,401] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-02 14:07:10,409] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-02 14:07:10,411] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-02 22:47:00,139] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-02 22:47:00,141] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-03 10:13:39,561] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-03 10:13:39,565] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-03 10:25:40,067] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-04-03 10:25:40,068] INFO Cleaner 0: Building offset map for __consumer_offsets-10... (kafka.log.LogCleaner)
[2017-04-03 10:25:40,174] INFO Cleaner 0: Building offset map for log __consumer_offsets-10 for 1 segments in offset range [0, 220). (kafka.log.LogCleaner)
[2017-04-03 10:25:40,214] INFO Cleaner 0: Offset map for log __consumer_offsets-10 complete. (kafka.log.LogCleaner)
[2017-04-03 10:25:40,229] INFO Cleaner 0: Cleaning log __consumer_offsets-10 (cleaning prior to Mon Apr 03 10:25:24 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-03 10:25:40,234] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-10 (largest timestamp Mon Apr 03 10:25:23 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-03 10:25:40,330] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-04-03 10:25:40,349] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
		at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
		at java.nio.file.Files.move(Unknown Source)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-03 10:25:40,351] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-03 12:40:18,023] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-03 12:40:18,039] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-03 12:40:18,093] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-04-03 12:40:18,093] INFO Cleaner 0: Building offset map for __consumer_offsets-10... (kafka.log.LogCleaner)
[2017-04-03 12:40:18,124] INFO Cleaner 0: Building offset map for log __consumer_offsets-10 for 1 segments in offset range [0, 220). (kafka.log.LogCleaner)
[2017-04-03 12:40:18,186] INFO Cleaner 0: Offset map for log __consumer_offsets-10 complete. (kafka.log.LogCleaner)
[2017-04-03 12:40:18,193] INFO Cleaner 0: Cleaning log __consumer_offsets-10 (cleaning prior to Mon Apr 03 10:25:24 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-03 12:40:18,208] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-10 (largest timestamp Mon Apr 03 10:25:23 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-03 12:40:18,293] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-04-03 12:40:18,355] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
		at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
		at java.nio.file.Files.move(Unknown Source)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-03 12:40:18,363] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-03 14:46:37,588] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-03 14:46:37,591] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-03 14:46:37,609] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-04-03 14:46:37,609] INFO Cleaner 0: Building offset map for __consumer_offsets-10... (kafka.log.LogCleaner)
[2017-04-03 14:46:37,625] INFO Cleaner 0: Building offset map for log __consumer_offsets-10 for 1 segments in offset range [0, 220). (kafka.log.LogCleaner)
[2017-04-03 14:46:37,656] INFO Cleaner 0: Offset map for log __consumer_offsets-10 complete. (kafka.log.LogCleaner)
[2017-04-03 14:46:37,656] INFO Cleaner 0: Cleaning log __consumer_offsets-10 (cleaning prior to Mon Apr 03 10:25:24 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-03 14:46:37,672] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-10 (largest timestamp Mon Apr 03 10:25:23 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-03 14:46:37,756] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-04-03 14:46:37,772] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
		at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
		at java.nio.file.Files.move(Unknown Source)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-03 14:46:37,772] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
